# Generated by Django 6.0.7 on 2026-08-04 00:12

import django.db.models.deletion
import utils.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppointmentReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Motif de rendez-vous",
                "verbose_name_plural": "Motifs de rendez-vous",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BusinessHour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("MONDAY", "Lundi"),
                            ("TUESDAY", "Mardi"),
                            ("WEDNESDAY", "Mercredi"),
                            ("THURSDAY", "Jeudi"),
                            ("FRIDAY", "Vendredi"),
                            ("SATURDAY", "Samedi"),
                            ("SUNDAY", "Dimanche"),
                        ],
                        db_index=True,
                        max_length=10,
                        verbose_name="Jour",
                    ),
                ),
                ("open_time", models.TimeField(verbose_name="Heure d'ouverture")),
                ("close_time", models.TimeField(verbose_name="Heure de fermeture")),
                ("is_closed", models.BooleanField(default=False, verbose_name="Fermé")),
                (
                    "reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="Motif de fermeture"
                    ),
                ),
            ],
            options={
                "verbose_name": "Horaire d'ouverture",
                "verbose_name_plural": "Horaires d'ouverture",
                "ordering": ["day_of_week", "open_time"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("day_of_week", "open_time", "close_time"),
                        name="unique_business_hour",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "guest_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Nom complet"
                    ),
                ),
                (
                    "guest_phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[utils.validators.IvoryCoastPhoneValidator()],
                        verbose_name="Téléphone",
                    ),
                ),
                (
                    "appointment_date",
                    models.DateField(db_index=True, verbose_name="Date"),
                ),
                (
                    "appointment_time",
                    models.TimeField(db_index=True, verbose_name="Heure"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("CONFIRMED", "Confirmée"),
                            ("CANCELLED", "Annulée"),
                            ("COMPLETED", "Terminée"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=15,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "motif",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="appointments.appointmentreason",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rendez-vous",
                "verbose_name_plural": "Rendez-vous",
                "ordering": ["appointment_date", "appointment_time"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("appointment_date", "appointment_time"),
                        name="unique_appointment_slot",
                    )
                ],
            },
        ),
    ]
