# Generated by Django 6.0.7 on 2026-08-04 17:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="appointment",
            name="unique_appointment_slot",
        ),
        migrations.AlterField(
            model_name="businesshour",
            name="close_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Heure de fermeture"
            ),
        ),
        migrations.AlterField(
            model_name="businesshour",
            name="open_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Heure d'ouverture"
            ),
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "CANCELLED"), _negated=True),
                fields=("appointment_date", "appointment_time"),
                name="unique_active_appointment_slot",
            ),
        ),
    ]
