# Generated by Django 6.0.7 on 2026-08-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="gender",
            field=models.CharField(
                choices=[
                    ("MEN", "Homme"),
                    ("WOMEN", "Femme"),
                    ("UNISEX", "Unisexe"),
                    ("KIDS", "Enfant"),
                ],
                db_index=True,
                default="UNISEX",
                max_length=10,
                verbose_name="Genre",
            ),
        ),
    ]
