# Generated by Django 6.0.7 on 2026-08-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_product_color_alter_productimage_is_primary_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="color",
            field=models.CharField(
                blank=True,
                db_index=True,
                default=None,
                max_length=100,
                null=True,
                verbose_name="Couleur",
            ),
        ),
    ]
